### ISSUE TITLE
[Story] See on-screen alert indicating the end of the beta process

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/sbl-project#201]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, after selecting "Continue to next step" from the Provide filing details page, I want to see an on-screen alert that indicates that I have completed the beta filing process, so that I know that I have reached the end and understand what I can do next. 

### Acceptance criteria

- Given that a filer has provided their filing details and clicked "Continue to next step," when they reach the "Sign and submit" page they are alerted that they have reached the end of the beta filing flow, then they will know that they can upload a new file to continue testing or email our support staff to provide feedback.
  - Warning alert at the top of the page
  - Success alert at the bottom of the page 

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- Add task

#### Back end
- Add task

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
Here's a screenshot reflecting the implementation of this feature. I think we can close without adding the related tasks since this feature was implemented and is now no longer live on beta, since we have since enabled Sign and submit. 
<img width="566" alt="Screenshot 2024-12-11 at 12 51 04 PM" src="https://github.com/user-attachments/assets/b551ac94-4ead-4141-9854-8173702090d2" />
<img width="539" alt="Screenshot 2024-12-11 at 12 52 18 PM" src="https://github.com/user-attachments/assets/acbc1fd7-b134-4da9-a814-9a832afb4a2f" />
