### ISSUE TITLE
[Story] Link to beta platform from cf.gov

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/sbl-project#257]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.
- https://github.com/cfpb/sbl-project/issues/7

### User story
- As a user, I want to access the beta platform via the CFPB website, so that I can browse the CFPB website for beta platform links and instructions. 

### Acceptance criteria
- Given a user is on cf.gov, when they navigate to the [small business lending database](https://www.consumerfinance.gov/data-research/small-business-lending/) page or the [registration and submission programs](https://www.consumerfinance.gov/compliance/registration-and-submission-programs/) page, then they can navigate the platform.

### Technical tasks

Team members should create technical tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
- [ ] Map story issue to the task analysis
- [ ] Validate user story
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness

#### Content
- [x] Content review and discussion
- [x] Stage content in Wagtail

**Comment by angelcardoz** [comment]
@chynnakeys, for https://www.consumerfinance.gov/compliance/registration-and-submission-programs/, I propose the following language. @natalia-fitzgerald, please let me know your thoughts.  Not sure, where in the page it should go since the page sorta follows alphabetical order, but not entirely. 

**The beta for the Small Business Lending Data Filing Platform** 

The CFPB is pleased to announce the availability of the beta platform for the small business lending data collection rule pursuant to section 1071 of the Dodd-Frank Act. We invite the participation of financial institutions and their technology partners to test the beta platform and share feedback with the CFPB on their experience. 

[Getting started with the beta platform
](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flinks-2.govdelivery.com%2FCL0%2Fhttps%3A%252F%252Ffiles.consumerfinance.gov%252Ff%252Fdocuments%252Fcfpb_sblbetaplatformlaunch-gettingstarted.pdf%2F1%2F010101918faa801c-b3935293-445e-4044-8614-7b9f7d5051f3-000000%2FqZ9EBj2Ftjs-GhUb3iibPHghIrRNOcZhYoAEAubtCas%3D367&data=05%7C02%7CAngel.CardozLopez%40cfpb.gov%7C717e8b14c1b74085bb7708dcd8d3dc52%7Cc817bf69ef414ed6ac5f1f44da3798c0%7C0%7C0%7C638623651694138853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=5aXZHg8ts85dRWr9C1cTOO8LGKEp6J8WbcaysDIXuus%3D&reserved=0)
[Access the beta platform
](https://sbl-beta.cfpb.gov/)

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
For this one: https://www.consumerfinance.gov/compliance/registration-and-submission-programs/ do you think the heading should be more generic, something like: 

- Small business lending 
- Small business lending data collection
- Or the name of the rule

For the link it could be: 
- Getting started with the beta platform
- Access the beta for the Small Business Lending Filing Platform

**Comment by angelcardoz** [comment]
@natalia-fitzgerald, great! Here's where we landed.

**Small Business Lending**

The CFPB’s rule on small business lending data requires covered financial institutions and voluntary reporters to maintain, report, and publicly disclose information about small business lending.

The CFPB is pleased to announce the availability of the beta platform for the small business lending data collection rule pursuant to section 1071 of the Dodd-Frank Act. We invite the participation of financial institutions and their technology partners to test the beta platform and share feedback with the CFPB on their experience.

[Getting started with the beta platform
](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flinks-2.govdelivery.com%2FCL0%2Fhttps%3A%252F%252Ffiles.consumerfinance.gov%252Ff%252Fdocuments%252Fcfpb_sblbetaplatformlaunch-gettingstarted.pdf%2F1%2F010101918faa801c-b3935293-445e-4044-8614-7b9f7d5051f3-000000%2FqZ9EBj2Ftjs-GhUb3iibPHghIrRNOcZhYoAEAubtCas%3D367&data=05%7C02%7CAngel.CardozLopez%40cfpb.gov%7C717e8b14c1b74085bb7708dcd8d3dc52%7Cc817bf69ef414ed6ac5f1f44da3798c0%7C0%7C0%7C638623651694138853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=5aXZHg8ts85dRWr9C1cTOO8LGKEp6J8WbcaysDIXuus%3D&reserved=0)
[Access the beta for the Small Business Lending Filing Platform
](https://sbl-beta.cfpb.gov/)

**Comment by angelcardoz** [comment]
@natalia-fitzgerald, for https://www.consumerfinance.gov/data-research/small-business-lending/, I propose similar language, except for the header. For the header I propose, "Test the beta platform".  Also, we wouldn't include the first paragraph since that's describe at the top of the page. Thoughts?

**Test the beta platform**

The CFPB is pleased to announce the availability of the beta platform for the small business lending data collection rule pursuant to section 1071 of the Dodd-Frank Act. We invite the participation of financial institutions and their technology partners to test the beta platform and share feedback with the CFPB on their experience.

Getting started with the beta platform

Access the beta for the Small Business Lending Filing Platform

**Comment by angelcardoz** [comment]
@chynnakeys, for https://www.consumerfinance.gov/data-research/small-business-lending/, let's do the following. Space was more limited so we are proposing abbreviated content. 

Test the beta platform

We invite the participation of financial institutions and their technology partners to test the beta platform and share feedback with the CFPB on their experience.

Learn to access the beta platform
Access the beta platform

For placement, I'm thinking it should go where "Resources for filers" currently lives or where " Download the data" is. Maybe we should talk about it.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
I reviewed the two sets of content and I have some additional recommendations to bring them into further consistency with one another and with the other content on the specific pages: 

<img width="793" alt="Screenshot 2024-09-25 at 11 54 53 AM" src="https://github.com/user-attachments/assets/a237f78f-6511-4b57-b2dc-89ae8b3d16a1">

If you want to add the "pursuant to section 1071 of the Dodd-Frank Act" language I think it fits better in the first paragraph. That way we can spell out the name of the beta platform in the second paragraph and then simplify the link text to be consistent with what we are doing on the other page.  
  
<img width="862" alt="Screenshot 2024-09-25 at 11 58 48 AM" src="https://github.com/user-attachments/assets/125ae41e-d1ca-47c6-a7ae-2e854a02d5a7">

**Comment by dan-padgett** [comment]
I think the revised language here reads a lot more clearly

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
As mentioned a little earlier, I am concerned about linking to the PDF for instructions on using the beta platform. 

Instead of linking to the "Getting started with the beta platform" PDF (ideally we wouldn't link to a PDF of a Word document from the site) can we instead link to the beta platform and the test files repo? 

The "Getting started" PDF contains the following information: 
- How to get an LEI
  - This is content that we include on the first page of the platform. It will be important for our testing to see whether this content is helpful for a user and gives them the information they need to get an LEI. 
  - There is some additional info related to LEI and the beta platform versus the production release but if this is important/essential maybe it should live on the homepage of the beta platform
- Test files for beta testing
  - The PDF includes a link to the test files repository on GitHub. I have heard that non-developers are not familiar with GitHub but currently this is where users must go to access these files. If this is the case perhaps it would be better to link to it directly from the website?   https://github.com/cfpb/RegTech-test-files/tree/main/sbl/demo_files
  
Here's a way we could do this: 
<img width="435" alt="Screenshot 2024-09-25 at 1 31 48 PM" src="https://github.com/user-attachments/assets/7dce38aa-696b-4a1b-8282-24ab9459c8d2">

**Comment by natalia-fitzgerald** [comment]
@chynnakeys @angelcardoz 
Another thing to follow up on with the stakeholder for this page: https://www.consumerfinance.gov/compliance/registration-and-submission-programs/

What should the ordering be for the page - alphabetical or something else? In the absence of any logical ordering I would recommend alphabetical for the sake of our users. 

Current ordering: 
<img width="669" alt="Screenshot 2024-09-25 at 2 01 25 PM" src="https://github.com/user-attachments/assets/8a725ad7-5e26-46c6-b688-6cef04499452">

Alphabetical ordering: 
<img width="905" alt="Screenshot 2024-09-25 at 2 03 41 PM" src="https://github.com/user-attachments/assets/71c8b91c-a6d6-46aa-9e47-637c5c7595f0">

**Comment by dan-padgett** [comment]
> If "Download test files" confuses users that land here: https://github.com/cfpb/RegTech-test-files/tree/main/sbl/demo_files we could instead word it as "Access test files"

If users are just going to another page, I think "Access test files" is better. "Download test files" suggests clicking the link initiates a download.

> We are pleased to announce the availability of the beta Small Business Lending Data Filing Platform. Financial institutions and their technology partners are invited to test the beta platform and share feedback on their experience.

Could we change the first sentence to "The Small Business Lending Data Filing Platform is now available."? That reads a lot better than the current phrasing and brings the sentence structure in line with the second sentence.

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
Can we make one more content adjustment? 

Current text: We are pleased to announce the availability of the beta Small Business Lending Data Filing Platform. 

Suggested change (both "open" and "availability" have been cleared):
- The beta for the Small Business Lending Data Filing Platform is now open.
- The beta for the Small Business Lending Data Filing Platform is now available.

<img width="742" alt="Screenshot 2024-09-25 at 4 12 01 PM" src="https://github.com/user-attachments/assets/95472771-7427-46a8-94ea-bcc63bf1bd1f">
<img width="816" alt="Screenshot 2024-09-25 at 4 21 47 PM" src="https://github.com/user-attachments/assets/c555e3eb-d0d1-4673-8b7a-eaded8c22e71">

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @chynnakeys 
Have we completed this story? I show that both pages are now live on cf.gov. 
- https://www.consumerfinance.gov/compliance/registration-and-submission-programs/
![Image](https://github.com/user-attachments/assets/1d54344f-8f83-48ad-9037-923af91240d6)

- https://www.consumerfinance.gov/data-research/small-business-lending/ 
![Image](https://github.com/user-attachments/assets/106d20b8-6115-4410-af67-117f91271d80)
