### ISSUE TITLE
[Task] Add a privacy act notice

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/sbl-project#41]
As any visitor to the homepage, I want to understand my rights regarding the privacy act.

### Acceptance criteria

- When I view the homepage, I should be able to see at a glance that I am protected by the privacy act and I click a link to learn more.

### Depends on

- #29 

### Context

<img width="1033" alt="274596562-9f04ac2b-ed3a-48f1-a82f-9e527cece4bb" src="https://github.com/cfpb/sbl-project/assets/19983248/2f2b1ec6-e1fc-478e-ba90-d04961a3edb2">

**Comment by natalia-fitzgerald** [comment]
@chynnakeys @angelcardoz 
Can we change the first sentence to read: "The Consumer Financial Protection Bureau (CFPB) is collecting data to test the functionality of the small business lending data submission platform."

**Comment by natalia-fitzgerald** [comment]
@chynnakeys @angelcardoz 

Can we also update the way we reference the webpage? 

"Participation is voluntary. If you choose to participate, the CFPB will collect your first and last name to test the "Complete your user profile" page. The CFPB will not use the data for any other purpose besides testing."

**Comment by angelcardoz** [comment]
@chynnakeys,  the notice is explicit about first and last name, but we are also testing LEI and other financial institution information tied to LEI. 

Is LEI or any other institution information considered "live data"?

**Comment by natalia-fitzgerald** [comment]
@chynnakeys @angelcardoz 
How's this? 
- Changed "Small Business Lending system" to "small business lending data submission platform"
- Changed "test the User Profile page" to "test the "Complete your user profile" page"...we have a different page called the "View user profile" so I don't want to confuse the user. BUT if we have to keep vague like it as is I would want to lowercase "user profile page" since this is not a proper name for that page
- Should the reg be linked? 
<img width="753" alt="Screenshot 2024-05-28 at 11 54 33 PM" src="https://github.com/cfpb/sbl-project/assets/77348967/46121dd3-135e-47d3-8b8a-c484762e1ca8">
<img width="373" alt="Screenshot 2024-05-28 at 11 54 50 PM" src="https://github.com/cfpb/sbl-project/assets/77348967/7dfb8810-1860-49f5-8ee6-a1cf2e7e3f5d">

**Comment by chynnakeys** [comment]
> @chynnakeys, the notice is explicit about first and last name, but we are also testing LEI and other financial institution information tied to LEI. Do we need to mention this as well?
> 
> Is LEI or any other institution information considered "live data"?

no, this is not considered "live data". that would fall into the FI3 information. Live data = SBLAR data

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach
I think all work on this launched with beta. Can we go ahead and close this ticket?

**Comment by billhimmelsbach** [comment]
Sounds good @natalia-fitzgerald!
