### ISSUE TITLE
Establish a consistent approach to user stories, acceptance criteria, and technical tasks and build GH template

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#81]
The purpose of this issue is for the team to collaborate on a consistent approach to user stories, acceptance criteria, and technical tasks. Here's an example of what the template could look like. 

### Title
[Story] Start with verb that describes user action (pull from the "I want to" part of the user story)

---

### Epic
Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.
- Add link to the parent epic

### User story

- As a [user type], I want to [take some action], so that [reason for action]. 

### Acceptance criteria

- Given [some context or conditions], when [the action that is performed], then [the expected observable outcome or behavior].

### Technical tasks
Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
Next step here is to build the GH template.

**Comment by angelcardoz** [comment]
@natalia-fitzgerald  and @dan-padgett, I ran into some styling limitations when configuring the issue templates. They looked off. Instead of the original structure (see image below), I'm proposing the second image. Thoughts?

Original:
![Image](https://github.com/cfpb/sbl-project/assets/148097357/d1190a2f-c4c6-4941-91f6-bd3d517c8f5d)

Proposed:
![Image](https://github.com/cfpb/sbl-project/assets/148097357/ed7bf881-5fec-48ab-aadd-afcb026186df)

**Comment by angelcardoz** [comment]
@dan-padgett, thank you. Natalia and I figured out a way to do it yesterday. All done, kept the original recommendation. Submitted the pull request and waiting for review. Once review is complete and the file is merged, it should be available as one of the templates.
